-- MySQL Script generated by MySQL Workbench
-- Fri Jun 17 10:17:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sitelivros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sitelivros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sitelivros` DEFAULT CHARACTER SET utf8 ;
USE `sitelivros` ;

-- -----------------------------------------------------
-- Table `sitelivros`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitelivros`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitelivros`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitelivros`.`post` (
  `idpost` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `image` VARCHAR(255) NULL,
  `contact` VARCHAR(255) NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idpost`),
  INDEX `fk_post_user_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `sitelivros`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
